[tool.poetry]
name = "hello-world"
version = "0.1.0"
description = "a hello world project"
authors = "dong@toggle.ai"
readme = "README.md"

[tool.poetry.dev-dependencies]
coverage = "7.0.1"
pre-commit = "3.0.0"
pytest = "7.2.1"

[tool.poetry.dependencies]
