name: Build
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - '**'

jobs:
  build:
    name: Test
    uses: ./.github/workflows/test-python.yml
    secrets: inherit
    with:
      python-versions: "['3.9', '3.10', '3.11']"
      dependency-management: 'poetry'
      coverage-threshold: 70
      use_tox: 'n'


#  image:
#    name: Image
#    uses: ./.github/workflows/build-python.yml
#    secrets: inherit
#    with:
#      dockerfile: ./docker/Dockerfile
#      runs-as: service
#      python-version: '3.8.3-slim'
#      push-image: ${{github.ref_name == 'main'}}
