name: Build
on:
  push:
    branches:
      - '**'

jobs:
  image:
    name: Image
    uses: ./.github/workflows/build-python.yml
    secrets: inherit
    with:
      dockerfile: ./docker/Dockerfile
      runs-as: service
      python-version: '3.8.3-slim'
      push-image: ${{github.ref_name == 'main'}}
