name: Build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Test
    uses: ./.github/workflows/test-python.yml
    with:
      python-version: '3.10'
      dependency-management: 'pip'


  image:
    name: Image
    uses: ./.github/workflows/build-python.yml
    secrets: inherit
    with:
      dockerfile: ./docker/Dockerfile
      runs-as: service
      python-version: '3.8.3-slim'
      push-image: ${{github.ref_name == 'main'}}
