on:
  workflow_call:
    inputs:
      python-version:
        description: Version of python used during testing
        required: true
        type: string
      dependency-management:
        description: Do you use pip or poetry to install dependencies
        required: true
        type: string

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies (Pip)
        if: inputs.dependency-management == 'pip'
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install dependencies (Poetry)
        if: inputs.dependency-management == 'poetry'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false
          poetry add flake8 pytest
          poetry install
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Test with pytest
        run: |
          pytest